"use client";

import {
  Award,
  CheckCircle2,
  Crown,
  Shield,
  TrendingUp,
} from "lucide-react";

const systemRanks = [
  {
    name: "Master",
    deposit: "$10,000",
    icon: Shield,
  },
  {
    name: "Royal",
    deposit: "$20,000",
    icon: Award,
  },
  {
    name: "Empire",
    deposit: "$40,000",
    icon: TrendingUp,
  },
  {
    name: "Ambassador",
    deposit: "$70,000",
    icon: Crown,
  },
  {
    name: "Crown Ambassador",
    deposit: "$100,000",
    icon: Crown,
  },
];



export default function SystemRankPage() {
  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="font-display text-xl font-semibold text-ink">
          System Rank
        </h1>

        <p className="mt-1 text-sm text-steel">
          View System Rank requirements and monthly Equity Bonus structure.
        </p>
      </div>

      {/* Current Rank */}
      <div className="rounded-2xl border border-line bg-white p-6 shadow-sm">
        <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-sm font-medium text-steel">
              Your Current System Rank
            </p>

            <h2 className="mt-1 font-display text-2xl font-bold text-ink">
              Master
            </h2>

            <p className="mt-2 text-sm text-steel">
              System Rank is calculated using your Total Team Deposit.
            </p>
          </div>

          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-blue/10 text-blue">
            <Award size={30} />
          </div>
        </div>
      </div>

      {/* Important Logic */}
      <div className="rounded-2xl border border-line bg-white p-6 shadow-sm">
        <h2 className="font-display text-lg font-semibold text-ink">
          Rank Achievement Logic
        </h2>

        <p className="mt-2 text-sm leading-6 text-steel">
          System Rank is based on the Total Team Deposit generated by the
          IB&apos;s complete team/downline according to the system&apos;s team
          hierarchy.
        </p>

        <div className="mt-4 rounded-xl bg-paper p-4">
          <p className="text-sm font-semibold text-ink">
            Important
          </p>

          <p className="mt-1 text-sm text-steel">
            Your personal deposit is not used to calculate System Rank.
            Only Total Team Deposit is considered.
          </p>
        </div>
      </div>

      {/* System Ranks */}
      <div className="rounded-2xl border border-line bg-white p-6 shadow-sm">
        <div className="mb-5">
          <h2 className="font-display text-lg font-semibold text-ink">
            System Ranks
          </h2>

          <p className="mt-1 text-sm text-steel">
            Rank requirements based on Total Team Deposit.
          </p>
        </div>

        <div className="space-y-3">
          {systemRanks.map((rank, index) => {
            const Icon = rank.icon;

            return (
              <div
                key={rank.name}
                className="flex items-center gap-4 rounded-xl border border-line p-4"
              >
                <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-blue/10 text-blue">
                  <Icon size={20} />
                </div>

                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-xs font-semibold text-steel">
                      #{index + 1}
                    </span>

                    <h3 className="font-semibold text-ink">
                      {rank.name}
                    </h3>
                  </div>

                  <p className="mt-1 text-sm text-steel">
                    Required Total Team Deposit
                  </p>
                </div>

                <div className="text-right">
                  <p className="font-semibold text-ink">
                    {rank.deposit}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Lifetime Rank */}
      <div className="rounded-2xl border border-line bg-white p-6 shadow-sm">
        <div className="flex gap-4">
          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-green-50 text-green-600">
            <CheckCircle2 size={21} />
          </div>

          <div>
            <h2 className="font-display text-lg font-semibold text-ink">
              Lifetime System Rank
            </h2>

            <p className="mt-2 text-sm leading-6 text-steel">
              Once a System Rank is achieved, it is considered lifetime and
              does not automatically expire if the user&apos;s equity or team
              deposit later decreases.
            </p>

            <p className="mt-2 text-sm leading-6 text-steel">
              The Admin can manually change, remove, or assign a different
              System Rank to a user.
            </p>
          </div>
        </div>
      </div>

      </div>
  );
}